languageCode = "en-us"
title = "JonathanDavidson.info"

[module]
  [[module.imports]]
    path = "github.com/imfing/hextra"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10
  [[menus.main]]
    name = 'Bio'
    pageRef = '/bio'
    weight = 20
  # [[menus.main]]
  #   name = 'Blog'
  #   pageRef = '/blog'
  #   weight = 30
  [[menus.main]]
    name = 'Contact'
    pageRef = '/contact'
    weight = 40
  [[menus.main]]
    name = 'GitHub'
    weight = 50
    url = 'https://github.com/jonathandavidson'
    [menus.main.params]
      icon = 'github'
  [[menus.main]]
    name = 'LinkedIn'
    weight = 60
    url = 'https://www.linkedin.com/in/jonathan-davidson-9345279/'
    [menus.main.params]
      icon = 'linkedin'

[params]
  externalLinkDecoration = true
  [params.navbar]
    [params.navbar.logo]
      path = 'images/jd-logo.svg'
  [params.footer]
    displayPoweredBy = false
    displayCopyright = true
  [params.theme]
    default = 'dark'
