languageCode = "en-us"
title = "JonathanDavidson.info"

[module]
  [[module.imports]]
    path = "github.com/imfing/hextra"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10
  [[menus.main]]
    name = 'Bio'
    pageRef = '/bio'
    weight = 20
  # [[menus.main]]
  #   name = 'Blog'
  #   pageRef = '/blog'
  #   weight = 30
  [[menus.main]]
    name = 'Contact'
    pageRef = '/contact'
    weight = 40

[params]
  [params.navbar]
    [params.navbar.logo]
      path = 'images/jd-logo.svg'
  [params.footer]
    displayPoweredBy = false
    displayCopyright = true
  [params.theme]
    default = 'light'
